import { defineQuery } from 'next-sanity'

// Result types are generated by Sanity TypeGen (`sanity.types.ts`) from these
// queries; `client.fetch` infers them automatically via module augmentation.

// Landing list: lightweight, sortable fields, ranked best-first.
export const COFFEE_SHOPS_QUERY = defineQuery(/* groq */ `
  *[_type == "coffeeShop" && defined(slug.current)]
  | order(rating desc, name asc) {
    _id,
    name,
    "slug": slug.current,
    shortDescription,
    rating,
    priceLevel,
    mainImage{ ..., "lqip": asset->metadata.lqip }
  }
`)

// Slugs for generateStaticParams.
export const COFFEE_SHOP_SLUGS_QUERY = defineQuery(/* groq */ `
  *[_type == "coffeeShop" && defined(slug.current)]{ "slug": slug.current }
`)

// A single shop by slug for the detail page.
export const COFFEE_SHOP_QUERY = defineQuery(/* groq */ `
  *[_type == "coffeeShop" && slug.current == $slug][0]{
    _id,
    name,
    "slug": slug.current,
    shortDescription,
    rating,
    priceLevel,
    mainImage{ ..., "lqip": asset->metadata.lqip },
    description
  }
`)
