import { defineQuery } from 'next-sanity'

// Result types are generated by Sanity TypeGen (`sanity.types.ts`) from these
// queries; `client.fetch` infers them automatically via module augmentation.

// Equal-weighted mean of the three scores, mirrored in JS for the Studio
// preview (`sanity/lib/rating.ts`). The `defined` guard is needed because
// `math::avg` skips nulls instead of propagating them, which would rate a
// half-scored shop on the scores it happens to have; `required()` can't cover
// this, as it runs in the Studio but not on API writes. The `null` fallback
// stops TypeGen inferring a non-nullable `number`.
const RATING = /* groq */ `select(
    defined(scores.vibe) && defined(scores.coffee) && defined(scores.affordability) =>
      round(math::avg([scores.vibe, scores.coffee, scores.affordability]), 1),
    null
  )`

// Ranking on the sum is equivalent to ranking on the mean. Parenthesised
// because GROQ won't parse `a + b + c desc`.
const RATING_ORDER = /* groq */ `(scores.vibe + scores.coffee + scores.affordability)`

// Landing list: lightweight, sortable fields, ranked best-first.
export const COFFEE_SHOPS_QUERY = defineQuery(/* groq */ `
  *[_type == "coffeeShop" && defined(slug.current)]
  | order(${RATING_ORDER} desc, name asc) {
    _id,
    name,
    "slug": slug.current,
    shortDescription,
    "rating": ${RATING},
    "affordability": scores.affordability,
    dogFriendly,
    mainImage{ ..., "lqip": asset->metadata.lqip }
  }
`)

// Slugs for generateStaticParams.
export const COFFEE_SHOP_SLUGS_QUERY = defineQuery(/* groq */ `
  *[_type == "coffeeShop" && defined(slug.current)]{ "slug": slug.current }
`)

// A single shop by slug for the detail page.
export const COFFEE_SHOP_QUERY = defineQuery(/* groq */ `
  *[_type == "coffeeShop" && slug.current == $slug][0]{
    _id,
    name,
    "slug": slug.current,
    shortDescription,
    "rating": ${RATING},
    "affordability": scores.affordability,
    dogFriendly,
    mainImage{ ..., "lqip": asset->metadata.lqip },
    description
  }
`)
